export const alphabetsPathPositions = [
  { id: 1, x: 44.7, y: 11.4 },
  { id: 2, x: 62.8, y: 15.0 },
  { id: 3, x: 34.6, y: 17.9 },
  { id: 4, x: 74.4, y: 22.0 },
  { id: 5, x: 23.2, y: 22.1 },
  { id: 6, x: 46.2, y: 24.2 },
  { id: 7, x: 74.7, y: 29.5 },
  { id: 8, x: 55.3, y: 32.8 },
  { id: 9, x: 30.7, y: 33.4 },
  { id: 10, x: 48.9, y: 40.7 },
  { id: 11, x: 50.8, y: 47.5 },
  { id: 12, x: 58.4, y: 52.9 },
  { id: 13, x: 44.5, y: 55.8 },
  { id: 14, x: 50.1, y: 61.4 },
  { id: 15, x: 36.7, y: 62.9 },
  { id: 16, x: 62.8, y: 62.9 },
  { id: 17, x: 21.8, y: 65.3 },
  { id: 18, x: 76.1, y: 65.2 },
  { id: 19, x: 48.0, y: 66.9 },
  { id: 20, x: 69.4, y: 70.7 },
  { id: 21, x: 14.5, y: 72.8 },
  { id: 22, x: 27.6, y: 72.7 },
  { id: 23, x: 83.9, y: 72.8 },
  { id: 24, x: 38.6, y: 75.6 },
  { id: 25, x: 56.1, y: 75.6 },
  { id: 26, x: 75.2, y: 78.5 },
  { id: 27, x: 26.0, y: 81.1 },
  { id: 28, x: 48.5, y: 81.0 },
  { id: 29, x: 64.5, y: 81.2 },
  { id: 30, x: 82.7, y: 82.5 },
  { id: 31, x: 11.2, y: 83.9 },
  { id: 32, x: 35.8, y: 86.0 },
  { id: 33, x: 58.4, y: 85.9 },
  { id: 34, x: 75.2, y: 87.9 },
  { id: 35, x: 19.3, y: 90.4 },
  { id: 36, x: 46.4, y: 92.5 },
  { id: 37, x: 64.5, y: 92.4 },
];

export const alphabetsPathConfig = {
  totalLessons: 37,
  image: '/alphabets_tree.png',
  lessons: [
    { id: 'hiragana-row-vowels', lessonId: 'hiragana-row-vowels', sectionSlug: 'hiragana', lessonSlug: 'row-vowels', kana: 'あ', titleKey: 'skillTree.alphabets.nodes.hiraganaVowels' },
    { id: 'hiragana-row-k', lessonId: 'hiragana-row-k', sectionSlug: 'hiragana', lessonSlug: 'row-k', kana: 'か', titleKey: 'skillTree.alphabets.nodes.hiraganaK' },
    { id: 'hiragana-cumulative-vowels-k', lessonId: 'hiragana-cumulative-vowels-k', sectionSlug: 'hiragana', lessonSlug: 'cumulative-vowels-k', kana: 'あか', titleKey: 'skillTree.alphabets.nodes.hiraganaVowelsKPractice' },
    { id: 'hiragana-row-s', lessonId: 'hiragana-row-s', sectionSlug: 'hiragana', lessonSlug: 'row-s', kana: 'さ', titleKey: 'skillTree.alphabets.nodes.hiraganaS' },
    { id: 'hiragana-row-t', lessonId: 'hiragana-row-t', sectionSlug: 'hiragana', lessonSlug: 'row-t', kana: 'た', titleKey: 'skillTree.alphabets.nodes.hiraganaT' },
    { id: 'hiragana-cumulative-s-t', lessonId: 'hiragana-cumulative-s-t', sectionSlug: 'hiragana', lessonSlug: 'cumulative-s-t', kana: 'さた', titleKey: 'skillTree.alphabets.nodes.hiraganaSTPractice' },
    { id: 'hiragana-review-1', lessonId: 'hiragana-review-1', sectionSlug: 'hiragana', lessonSlug: 'review-1', kana: '復', titleKey: 'skillTree.alphabets.nodes.hiraganaReviewOne' },
    { id: 'hiragana-row-n', lessonId: 'hiragana-row-n', sectionSlug: 'hiragana', lessonSlug: 'row-n', kana: 'な', titleKey: 'skillTree.alphabets.nodes.hiraganaN' },
    { id: 'hiragana-row-h', lessonId: 'hiragana-row-h', sectionSlug: 'hiragana', lessonSlug: 'row-h', kana: 'は', titleKey: 'skillTree.alphabets.nodes.hiraganaH' },
    { id: 'hiragana-cumulative-n-h', lessonId: 'hiragana-cumulative-n-h', sectionSlug: 'hiragana', lessonSlug: 'cumulative-n-h', kana: 'なは', titleKey: 'skillTree.alphabets.nodes.hiraganaNHPractice' },
    { id: 'hiragana-row-m', lessonId: 'hiragana-row-m', sectionSlug: 'hiragana', lessonSlug: 'row-m', kana: 'ま', titleKey: 'skillTree.alphabets.nodes.hiraganaM' },
    { id: 'hiragana-row-y', lessonId: 'hiragana-row-y', sectionSlug: 'hiragana', lessonSlug: 'row-y', kana: 'や', titleKey: 'skillTree.alphabets.nodes.hiraganaY' },
    { id: 'hiragana-cumulative-m-y', lessonId: 'hiragana-cumulative-m-y', sectionSlug: 'hiragana', lessonSlug: 'cumulative-m-y', kana: 'まや', titleKey: 'skillTree.alphabets.nodes.hiraganaMYPractice' },
    { id: 'hiragana-review-2', lessonId: 'hiragana-review-2', sectionSlug: 'hiragana', lessonSlug: 'review-2', kana: '復', titleKey: 'skillTree.alphabets.nodes.hiraganaReviewTwo' },
    { id: 'hiragana-row-r', lessonId: 'hiragana-row-r', sectionSlug: 'hiragana', lessonSlug: 'row-r', kana: 'ら', titleKey: 'skillTree.alphabets.nodes.hiraganaR' },
    { id: 'hiragana-row-w', lessonId: 'hiragana-row-w', sectionSlug: 'hiragana', lessonSlug: 'row-w', kana: 'わ', titleKey: 'skillTree.alphabets.nodes.hiraganaW' },
    { id: 'hiragana-cumulative-r-w', lessonId: 'hiragana-cumulative-r-w', sectionSlug: 'hiragana', lessonSlug: 'cumulative-r-w', kana: 'らわ', titleKey: 'skillTree.alphabets.nodes.hiraganaRWPractice' },
    { id: 'hiragana-review-final', lessonId: 'hiragana-review-final', sectionSlug: 'hiragana', lessonSlug: 'review-final', kana: '総', titleKey: 'skillTree.alphabets.nodes.hiraganaFinalReview' },
    { id: 'katakana-row-vowels', lessonId: 'katakana-row-vowels', sectionSlug: 'katakana', lessonSlug: 'row-vowels', kana: 'ア', titleKey: 'skillTree.alphabets.nodes.katakanaVowels' },
    { id: 'katakana-row-k', lessonId: 'katakana-row-k', sectionSlug: 'katakana', lessonSlug: 'row-k', kana: 'カ', titleKey: 'skillTree.alphabets.nodes.katakanaK' },
    { id: 'katakana-cumulative-vowels-k', lessonId: 'katakana-cumulative-vowels-k', sectionSlug: 'katakana', lessonSlug: 'cumulative-vowels-k', kana: 'アカ', titleKey: 'skillTree.alphabets.nodes.katakanaVowelsKPractice' },
    { id: 'katakana-row-s', lessonId: 'katakana-row-s', sectionSlug: 'katakana', lessonSlug: 'row-s', kana: 'サ', titleKey: 'skillTree.alphabets.nodes.katakanaS' },
    { id: 'katakana-row-t', lessonId: 'katakana-row-t', sectionSlug: 'katakana', lessonSlug: 'row-t', kana: 'タ', titleKey: 'skillTree.alphabets.nodes.katakanaT' },
    { id: 'katakana-cumulative-s-t', lessonId: 'katakana-cumulative-s-t', sectionSlug: 'katakana', lessonSlug: 'cumulative-s-t', kana: 'サタ', titleKey: 'skillTree.alphabets.nodes.katakanaSTPractice' },
    { id: 'katakana-review-1', lessonId: 'katakana-review-1', sectionSlug: 'katakana', lessonSlug: 'review-1', kana: '復', titleKey: 'skillTree.alphabets.nodes.katakanaReviewOne' },
    { id: 'katakana-row-n', lessonId: 'katakana-row-n', sectionSlug: 'katakana', lessonSlug: 'row-n', kana: 'ナ', titleKey: 'skillTree.alphabets.nodes.katakanaN' },
    { id: 'katakana-row-h', lessonId: 'katakana-row-h', sectionSlug: 'katakana', lessonSlug: 'row-h', kana: 'ハ', titleKey: 'skillTree.alphabets.nodes.katakanaH' },
    { id: 'katakana-cumulative-n-h', lessonId: 'katakana-cumulative-n-h', sectionSlug: 'katakana', lessonSlug: 'cumulative-n-h', kana: 'ナハ', titleKey: 'skillTree.alphabets.nodes.katakanaNHPractice' },
    { id: 'katakana-row-m', lessonId: 'katakana-row-m', sectionSlug: 'katakana', lessonSlug: 'row-m', kana: 'マ', titleKey: 'skillTree.alphabets.nodes.katakanaM' },
    { id: 'katakana-row-y', lessonId: 'katakana-row-y', sectionSlug: 'katakana', lessonSlug: 'row-y', kana: 'ヤ', titleKey: 'skillTree.alphabets.nodes.katakanaY' },
    { id: 'katakana-cumulative-m-y', lessonId: 'katakana-cumulative-m-y', sectionSlug: 'katakana', lessonSlug: 'cumulative-m-y', kana: 'マヤ', titleKey: 'skillTree.alphabets.nodes.katakanaMYPractice' },
    { id: 'katakana-review-2', lessonId: 'katakana-review-2', sectionSlug: 'katakana', lessonSlug: 'review-2', kana: '復', titleKey: 'skillTree.alphabets.nodes.katakanaReviewTwo' },
    { id: 'katakana-row-r', lessonId: 'katakana-row-r', sectionSlug: 'katakana', lessonSlug: 'row-r', kana: 'ラ', titleKey: 'skillTree.alphabets.nodes.katakanaR' },
    { id: 'katakana-row-w', lessonId: 'katakana-row-w', sectionSlug: 'katakana', lessonSlug: 'row-w', kana: 'ワ', titleKey: 'skillTree.alphabets.nodes.katakanaW' },
    { id: 'katakana-cumulative-r-w', lessonId: 'katakana-cumulative-r-w', sectionSlug: 'katakana', lessonSlug: 'cumulative-r-w', kana: 'ラワ', titleKey: 'skillTree.alphabets.nodes.katakanaRWPractice' },
    { id: 'katakana-review-final', lessonId: 'katakana-review-final', sectionSlug: 'katakana', lessonSlug: 'review-final', kana: '総', titleKey: 'skillTree.alphabets.nodes.katakanaFinalReview' },
    { id: 'alphabets-final-test', kana: '試', titleKey: 'skillTree.alphabets.nodes.finalTest' },
  ],
};
